services:
  coturn:
    image: coturn/coturn:4.6.3
    container_name: proconnectiv-coturn
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf:ro
    command:
      - -c
      - /etc/coturn/turnserver.conf
